#!/usr/bin/env python3
"""
generate_daily_brief.py – Produce a daily summary from threats and sweep data.
Outputs daily_brief.md (Markdown) and daily_brief.html (for the site).
"""

import json
from datetime import datetime
from pathlib import Path

def load_json(filepath, default=None):
    if Path(filepath).exists():
        with open(filepath, 'r') as f:
            return json.load(f)
    return default if default is not None else {}

def main():
    # Load data
    threats_data = load_json("threats.json")
    sweep_data = load_json("sweep_report.json")
    threats = threats_data.get('threats', [])
    gsci = threats_data.get('gsci', '--')
    timestamp = sweep_data.get('timestamp', datetime.now().isoformat())

    # Sort by priority and take top 5
    top = sorted(threats, key=lambda x: x.get('priority_score', 0), reverse=True)[:5]

    # Build Markdown brief
    md = f"# Cathedral Daily Brief – {datetime.now().strftime('%d %b %Y')}\n\n"
    md += f"**GSCI:** {gsci}  \n"
    md += f"**Last sweep:** {timestamp}\n\n"
    md += "## Top Threats\n\n"
    for t in top:
        tid = t.get('id', '')
        name = t.get('name', 'Unknown')
        scp = t.get('scp', 0) * 100
        priority = t.get('priority_score', 0)
        desc = t.get('description', '')[:120]
        md += f"### {tid} – {name}\n"
        md += f"- **SCP:** {scp:.1f}%  \n"
        md += f"- **Priority:** {priority:.0f}  \n"
        md += f"- {desc}...\n\n"

    # Add events from sweep
    events = sweep_data.get('events', [])
    if events:
        md += "## Recent Events\n\n"
        for ev in events[:5]:
            md += f"- {ev.get('description', '')[:100]}\n"
    md += "\n---\n*Generated by Cathedral Engine*"

    # Save Markdown
    with open("daily_brief.md", "w") as f:
        f.write(md)

    # Build HTML version for the site
    html = f"""<!DOCTYPE html>
<html lang="en">
<head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Cathedral Daily Brief</title>
<style>body{{font-family:system-ui; max-width:800px; margin:2rem auto; padding:0 1.5rem; line-height:1.6;}}
h1{{border-bottom:2px solid #7c4dff; padding-bottom:0.3rem;}}
.meta{{color:#666; font-size:0.9rem;}}
.top-threat{{background:#f5f0fa; padding:0.8rem 1rem; border-radius:12px; margin-bottom:1rem; border-left:4px solid #7c4dff;}}
.events{{background:#fafafa; padding:0.8rem 1rem; border-radius:12px;}}
.footer{{margin-top:2rem; font-style:italic; color:#888; border-top:1px solid #ddd; padding-top:1rem;}}
</style>
</head>
<body>
<h1>Cathedral Daily Brief</h1>
<div class="meta"><strong>GSCI:</strong> {gsci} · Last sweep: {timestamp[:10]}</div>
<h2>Top Threats</h2>
"""
    for t in top:
        tid = t.get('id', '')
        name = t.get('name', 'Unknown')
        scp = t.get('scp', 0) * 100
        priority = t.get('priority_score', 0)
        desc = t.get('description', '')[:120]
        html += f"""
<div class="top-threat">
  <strong>{tid} – {name}</strong><br>
  SCP: {scp:.1f}% · Priority: {priority:.0f}<br>
  {desc}...
</div>"""
    if events:
        html += "<h2>Recent Events</h2><div class='events'><ul>"
        for ev in events[:5]:
            html += f"<li>{ev.get('description', '')[:100]}</li>"
        html += "</ul></div>"
    html += f"""
<div class="footer">Always and Forever, Coco.<br>Generated {datetime.now().strftime('%d %b %Y %H:%M')}</div>
</body>
</html>"""

    with open("daily_brief.html", "w") as f:
        f.write(html)

    print("✅ Daily brief generated (Markdown + HTML)")

if __name__ == "__main__":
    main()
